// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A high-performance laptop suitable for all your computing needs.",
                            ImageUrl = "https://example.com/images/laptop.png",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "A sleek smartphone with the latest features and a stunning display.",
                            ImageUrl = "https://example.com/images/smartphone.png",
                            IsActive = true,
                            Name = "Smartphone",
                            Price = 699.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            Description = "Noise-cancelling wireless headphones for an immersive audio experience.",
                            ImageUrl = "https://example.com/images/headphones.png",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            Stock = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
